### ISSUE TITLE
注意空白鍵與 tab 鍵的使用

### ISSUE THREAD

**Issue by lili668668** [tsukiamaoto/Blog_redux#7]
https://github.com/tsukiamaoto/Blog_redux/blob/839aebab47b8e481185b292c4b2883e9f417d842/ui/src/css/home.css#L2-L50

你可以在編輯器設定自己要全部使用空白鍵代替 tab 鍵，總之不要有

1. 無意義的縮排
2. 縮排空格數量不一

之類的問題留下

**Comment by chunkai1312** [comment]
@tsukiamaoto 請用空白鍵 2 格取代 tab, 可以用 `.editorconfig`
